{{- if .Values.domain }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: web-http
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ .Values.domain }}`)
      kind: Rule
      middlewares:
        - name: redirect-https
      services:
        - name: web
          port: {{ .Values.port }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: web-https
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.domain }}`) && PathPrefix(`/graphql`)
      kind: Rule
      services:
        - name: api
          port: 4000
    - match: Host(`{{ .Values.domain }}`)
      kind: Rule
      services:
        - name: web
          port: {{ .Values.port }}
  tls:
    certResolver: {{ .Values.certResolver }}
{{- end }}
