apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "player-sheet.fullname" . }}-api
  labels:
    {{- include "player-sheet.api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      {{- include "player-sheet.api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "player-sheet.api.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: api
          image: "{{ .Values.api.image }}:{{ .Values.api.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ .Values.api.port }}
              protocol: TCP
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "player-sheet.fullname" . }}-config
                  key: API_PORT
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: {{ include "player-sheet.fullname" . }}-config
                  key: API_NODE_ENV
            - name: CORS_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: {{ include "player-sheet.fullname" . }}-config
                  key: API_CORS_ORIGIN
            - name: JWT_EXPIRES_IN
              valueFrom:
                configMapKeyRef:
                  name: {{ include "player-sheet.fullname" . }}-config
                  key: JWT_EXPIRES_IN
            - name: JWT_REFRESH_EXPIRES_IN
              valueFrom:
                configMapKeyRef:
                  name: {{ include "player-sheet.fullname" . }}-config
                  key: JWT_REFRESH_EXPIRES_IN
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "player-sheet.fullname" . }}-secrets
                  key: JWT_SECRET
            - name: JWT_REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "player-sheet.fullname" . }}-secrets
                  key: JWT_REFRESH_SECRET
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "player-sheet.fullname" . }}-secrets
                  key: MONGODB_URI
          livenessProbe:
            httpGet:
              path: /graphql?query=%7B__typename%7D
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /graphql?query=%7B__typename%7D
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
