apiVersion: v1
kind: Service
metadata:
  name: {{ include "player-sheet.fullname" . }}-api
  labels:
    {{- include "player-sheet.api.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.api.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "player-sheet.api.selectorLabels" . | nindent 4 }}
