{{- if .Values.mongodb.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "player-sheet.fullname" . }}-mongodb
  labels:
    {{- include "player-sheet.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: mongodb
      protocol: TCP
      name: mongodb
  selector:
    {{- include "player-sheet.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
{{- end }}
