apiVersion: v1
kind: Secret
metadata:
  name: {{ include "player-sheet.fullname" . }}-secrets
  labels:
    {{- include "player-sheet.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  JWT_REFRESH_SECRET: {{ .Values.secrets.jwtRefreshSecret | quote }}
  MONGODB_ROOT_PASSWORD: {{ .Values.secrets.mongodbRootPassword | quote }}
  MONGODB_URI: {{ include "player-sheet.mongodbUri" . | quote }}
