apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "player-sheet.fullname" . }}-web
  labels:
    {{- include "player-sheet.web.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      {{- include "player-sheet.web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "player-sheet.web.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: web
          image: "{{ .Values.web.image }}:{{ .Values.web.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ .Values.web.port }}
              protocol: TCP
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "player-sheet.fullname" . }}-config
                  key: WEB_PORT
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: {{ include "player-sheet.fullname" . }}-config
                  key: WEB_NODE_ENV
            - name: NEXT_PUBLIC_API_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "player-sheet.fullname" . }}-config
                  key: NEXT_PUBLIC_API_URL
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
