apiVersion: v1
kind: Service
metadata:
  name: {{ include "player-sheet.fullname" . }}-web
  labels:
    {{- include "player-sheet.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.web.port | int }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "player-sheet.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
