apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "player-sheet.fullname" . }}-web
  labels:
    {{- include "player-sheet.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.web.replicas | int }}
  selector:
    matchLabels:
      {{- include "player-sheet.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "player-sheet.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
    spec:
      containers:
        - name: web
          image: "{{ .Values.web.image }}:{{ .Values.web.tag }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: {{ .Values.web.port | int }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "player-sheet.fullname" . }}-config
          env:
            - name: PORT
              value: "{{ .Values.web.port }}"
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
