apiVersion: v1
kind: Service
metadata:
  name: {{ include "player-sheet.fullname" . }}-web
  labels:
    {{- include "player-sheet.web.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.web.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "player-sheet.web.selectorLabels" . | nindent 4 }}
