apiVersion: v2
name: player-sheet
description: Cyberpunk Red Campaign Management App
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: mongodb
    version: "14.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: mongodb.enabled
